@startuml Wordle
'https://plantuml.com/class-diagram
skinparam groupInheritance 2
skinparam Linetype ortho

enum Status {
    INITIAL
    IN_PROGRESS
    WRONG
    PARTIAL
    CORRECT
}

abstract class AbstractLetter {
    + {abstract} getCharacter(): char
    + {abstract} setCharacter(c: char): void
    + {abstract} resetCharacter(): void
    + {abstract} getStatus(): Status
    + {abstract} setStatus(status: Status): void
    + {abstract} isNull(): boolean
    + equals(obj: Object): boolean
    + toString(): String
}
AbstractLetter --> Status

class Letter extends AbstractLetter {
    - status: Status
    - character: char
    + Letter(character: char)
    + Letter()
    + getCharacter(): char
    + setCharacter(character: char): void
    + resetCharacter(): void
    + getStatus(): Status
    + setStatus(status: Status): void
    + isNull(): boolean
}
Letter --> Status

abstract class AbstractWord {
    + {abstract} getLetter(index: int): AbstractLetter
    + {abstract} length(): int
    + {abstract} isEmpty(): boolean
    + {abstract} isFull(): boolean
    + {abstract} isCorrect(): boolean
    + {abstract} toString(): String
    + equals(obj: Object): boolean
}
AbstractWord --> AbstractLetter

class Word extends AbstractWord {
    - letters: AbstractLetter[]
    + Word(word: String)
    + Word(length: int)
    + getLetter(index: int): AbstractLetter
    + length(): int
    + isEmpty(): boolean
    + isFull(): boolean
    + isCorrect(): boolean
    + toString(): String
}
Word --> AbstractLetter

class ViewModel<T> {
    - state: T
    - viewName: String
    + ViewModel(state: T)
    + getState(): T
    + getViewName(): String
}

class ViewManagerModel extends ViewModel {
    + ViewManagerModel()
}

class ViewManager {
    - cardLayout: CardLayout
    - views: JPanel
    - viewManagerModel: ViewManagerModel
    + ViewManager(views: JPanel, cardLayout: CardLayout, viewManagerModel: ViewManagerModel)
    + propertyChange(evt: PropertyChangeEvent): void
}
ViewManager --> ViewManagerModel

class OptionsViewModel extends ViewModel {
    + OptionsViewModel()
}
OptionsViewModel --> OptionsState

class OptionsController {
    + OptionsController(OptionsInputBoundary)
    + execute(): void
}
OptionsController --> OptionsState
OptionsController --> OptionsInputBoundary

class OptionsPresenter extends OptionsOutputBoundary {
    + OptionsPresenter(ViewManagerModel, OptionsViewModel, StartViewModel)
    + prepareStartView(): void
}
OptionsPresenter --> OptionsViewModel
OptionsPresenter --> StartViewModel

interface OptionsOutputBoundary {
    + prepareStartView(): void
}

class OptionsState {
    - length: int
    - maxGuesses: int
    + OptionsState()
    + getTheme(): Theme
    + setTheme(theme: Theme): void
    + getLength(): int
    + setLength(length: int): void
    + getMaxGuesses(): int
    + setMaxGuesses(maxGuesses: int): void
    + getLanguage(): Language
    + setLanguage(language: Language): void
}
OptionsState --> Theme
OptionsState --> Language

interface OptionsInputBoundary {
    + {abstract} execute(inputData: OptionsState): void
}

class OptionsInteractor implements OptionsInputBoundary {
    + OptionsInteractor(OptionsDataAccessInterface, OptionsOutputBoundary)
    + execute(inputData: OptionsState): void
}
OptionsInteractor --> OptionsState
OptionsInteractor --> OptionsOutputBoundary
OptionsInteractor --> OptionsDataAccessInterface

interface OptionsDataAccessInterface {
    + getOptions(): OptionsState
    + saveOptions(options: OptionsState): void
}
OptionsDataAccessInterface ..* OptionsState

class OptionsView {
    - optionsController: OptionsController
    - viewName: String
    + OptionsView(OptionsViewModel)
}
OptionsView --> OptionsViewModel
OptionsView --> OptionsController


class EndView {
    - endController: EndController
    - viewName: String
    + EndView(EndViewModel)
}
EndView --* EndViewModel
EndView --* EndController

class EndViewModel extends ViewModel {
    + EndViewModel()
}
EndViewModel --> GameState

class EndPresenter implements EndOutputBoundary {
    + EndPresenter(ViewManagerModel, EndViewModel, GameViewModel, StartViewModel, OptionsViewModel)
    + prepareGameView(): void
    + prepareOptionsView(): void
    + prepareStartView(): void
}
EndPresenter --> EndViewModel
EndPresenter --> GameViewModel
EndPresenter --> StartViewModel
EndPresenter --> OptionsViewModel

interface EndOutputBoundary {
    + prepareGameView(options: OptionsState): void
    + prepareOptionsView(): void
    + prepareStartView(): void
}
EndOutputBoundary --> OptionsState

class EndController {
    + EndController(EndInputBoundary)
    + execute(): void
}
EndController --> EndInputBoundary
' EndController --> EndInputData

' class EndInputData {

' }

' class EndState {
'     - words: AbstractWord[]
'     - wordToGuess: AbstractWord
'     + EndState()
'     + toString(): String
'     + getWords(): AbstractWord[]
'     + setWords(words: AbstractWord[]): void
'     + getWordToGuess(): AbstractWord
'     + setWordToGuess(wordToGuess: AbstractWord): void
' }

interface EndInputBoundary {
    + {abstract} execute(endInputData: GameState): void
}
EndInputBoundary --> GameState

class EndInteractor implements EndInputBoundary {
    + EndInteractor(EndDataAccessInterface, EndOutputBoundary)
    + execute(endInputData: GameState): void
}
EndInteractor --> EndOutputBoundary
EndInteractor --> EndDataAccessInterface
EndInteractor --> GameState
    ' + drawFrame(frame: JFrame): void
    ' + exportResults(): String
    ' + copyResults(): void
interface EndDataAccessInterface

class GameViewModel extends ViewModel {
    + GameViewModel()
}

class GameView {
    - {static} SQUARE_SIZE: int
    - {static} MARGINS: int
    - {static} VIEW_NAME: String
    ~ shakeOffset: float
    - gameViewModel: GameViewModel
    - optionsViewModel: OptionsViewModel
    - gameController: GameController
    - menu: JButton
    - submit: JButton
    - gamePanel: JPanel
    + GameView(GameViewModel, OptionsViewModel)
    + actionPerformed(e: ActionEvent): void
    + propertyChange(evt: PropertyChangeEvent): void
    + paint(g: Graphics): void
    - setTheme(component: JComponent, theme: Theme): void
    - drawLetter(g: Graphics2D, letter: AbstractLetter, shape: Shape, x: int, y: int, size: int, current: boolean): void
    - getTransform(x: float, y: int, size: int): AffineTransform
    - drawBoxBackground(g: Graphics2D, letter: AbstractLetter, shape: Shape, transform: AffineTransform): void
    - drawBoxOutline(g: Graphics2D, shape: Shape, transform: AffineTransform): void
    - drawBoxLetter(g: Graphics2D, letter: AbstractLetter, x: int, y: int, size: int): void
    + getViewName(): String
    - getTheme(): Theme
    - createBufferPanel(): JPanel
    + setGameController(gameController: GameController): void
}
GameView --> GameViewModel
GameView --> OptionsViewModel
GameView --> GameController
GameView --> GameState
GameView --> AbstractLetter
GameView --> AbstractWord
GameView --* KeyAction
GameView --* WordShake

-class KeyAction {
    - view: GameView
    - type: String
    + KeyAction(view: GameView, type: String)
    + actionPerformed(e: ActionEvent): void
}
KeyAction --> GameView

-class WordShake {
    - view: GameView
    + WordShake(view: GameView)
    + run(): void
    - shake(time: double): float
}
WordShake --> GameView

class GameController {
    + {static} ENTER: String
    + {static} LETTER: String
    + {static} BACKSPACE: String
    - gameInteractor: GameInputBoundary
    + GameController(GameInputBoundary)
    + execute(gameInputData: GameState, e: ActionEvent): void
    + executeSubmit(gameInputData: GameState): void
    + switchToStartView(): void
    + switchToEndView(): void
}
GameController --> GameInputBoundary
GameController --> GameState

' class GameInputData {
'     - length: int
'     - maxGuesses: int
'     + GameInputData(length: int, maxGuesses: int)
'     + getLength(): int
'     + getMaxGuesses(): int
' }

interface GameInputBoundary {
    + {abstract} executeLetter(gameInputData: GameState, letter: char): void
    + {abstract} executeSubmit(gameInputData: GameState): void
    + {abstract} executeBackspace(gameInputData: GameState): void
    + {abstract} prepareStartView(): void
    + {abstract} prepareEndView(gameState: GameState)
}
GameInputBoundary --> GameState

    ' + {abstract} start(): void
    ' + {abstract} getStatus(): GameState
    ' + {abstract} update(input: char): GameState

interface GameOutputBoundary {
    + {abstract} updateGameView(state: GameState): void
    + {abstract} shakeWord(state: GameState): void
    + {abstract} prepareStartView(): void
    + {abstract} prepareEndView(state: GameState): void
}
GameOutputBoundary --> GameState

class GamePresenter implements GameOutputBoundary {
    - viewManagerModel: ViewManagerModel
    - gameViewModel: GameViewModel
    - startViewModel: StartViewModel
    - endViewModel: EndViewModel
    + GamePresenter(ViewManagerModel, GameViewModel, StartViewModel, EndViewModel)
    + updateGameView(gameState GameState): void
    + shakeWord(gameState: GameState): void
    + prepareStartView(): void
    + prepareEndView(): void
}
GamePresenter --> ViewManagerModel
GamePresenter --> GameViewModel
GamePresenter --> StartViewModel
GamePresenter --> EndViewModel
GamePresenter --> GameState

class GameInteractor implements GameInputBoundary {
    - gameDataAccess: GameDataAccessInterface
    - gamePresenter: GameOutputBoundary
    + GameInteractor(GameDataAccessInterface, GameOutputBoundary)
    + executeLetter(gameInputData: GameState, letter: char): void
    + executeSubmit(gameInputData: GameState): void
    + executeBackspace(gameInputData: GameState): void
    + prepareStartView(): void
    + prepareEndView(gameState: GameState): void
}
GameInteractor --> GameOutputBoundary
GameInteractor --> GameState
GameInteractor --> GameDataAccessInterface

    ' - wordChecker: WordChecker
    ' - status: GameStatus
    ' + GameInteractor(config: Map<String, Object>)
    ' + start(): void
    ' + getStatus(): GameStatus
    ' + update(input: char): GameStatus
    ' - generateWord(length: int): String

' class GameOutputData {
'     - currentGuess: int
'     - words: AbstractWord[]
'     - wordToGuess: AbstractWord
'     + GameOutputData()
'     + toString(): String
' }

interface GameDataAccessInterface {
    + getRandomWord(length: int, language: Language): String
    + isValidWord(word: String, language: Language): boolean
}
GameDataAccessInterface --> Language

class GameState {
    - {static} COLORS: Map<Status, String>
    - length: int
    - maxGuesses: int
    - language: Language
    - currentGuess: int
    - words: AbstractWord[]
    - wordToGuess: AbstractWord
    + GameState()
    + GameState(wordToGuess: AbstractWord, maxGuesses: int, language: Language)
    + GameState(wordToGuess: AbstractWord, maxGuesses: int)
    + GameState(wordToGuess: AbstractWord, words: AbstractWord[], language: Language)
    + GameState(wordToGuess: AbstractWord, words: AbstractWord[])
    - initializeEmptyWords(): void
    - initializeCurrentGuess(): void
    - initializeCurrentLetter(): void
    + toString(): String
    + getLength(): int
    + getMaxGuesses(): int
    + getLanguage(): Language
    + getCurrentGuess(): int
    + getCurrentLetter(): AbstractLetter
    + getCurrentLetterIndex(): int
    + getWords(): AbstractWord[]
    + getWordToGuess(): AbstractWord
    + nextLetter(character: char): void
    + previousLetter(): void
    - nextWord(): void
    - checkGuess(): Status[]
    + submit(): void
    + finished(): boolean
}
GameState --> AbstractWord
GameState --> Language
GameState --> AbstractLetter
GameState --> Status

class StatsController {
    + StatsController(StatsInputBoundary)
    + execute(): void
}
StatsController --> StatsInputBoundary
StatsController --> StatsInputData
class StatsPresenter implements StatsOutputBoundary {
    + StatsPresenter(ViewManagerModel, StatsViewModel, StartViewModel)
    + prepareSuccessView(): void
    + prepareFailView(): void
    + prepareDefaultView(): void
    + prepareStartView(): void
}
StatsPresenter --> StatsViewModel
StatsPresenter --> StartViewModel
StatsPresenter --> StatsOutputData

class StatsViewModel extends ViewModel {
    + StatsViewModel()
}
class StatsView {
    - statsController: StatsController
    - viewName: String
    + StatsView(StatsViewModel)
}
StatsView --> StatsViewModel
StatsView --> StatsController
class StatsInputData
interface StatsInputBoundary {
    + {abstract} execute(inputData: StatsInputData): void
}
class StatsInteractor implements StatsInputBoundary {
    + StatsInteractor(StatsDataAccessInterface, StatsOutputBoundary)
    + execute(inputData: StatsInputData): void
}
StatsInteractor --> StatsInputData
StatsInteractor --> StatsOutputBoundary
StatsInteractor --> StatsDataAccessInterface
interface StatsOutputBoundary {
    + prepareSuccessView(): void
    + prepareFailView(): void
    + prepareDefaultView(): void
    + prepareStartView(): void
}
interface StatsDataAccessInterface {
    + getStats(): StatsState
    + saveStats(stats: StatsState): void
}
StatsDataAccessInterface --> StatsState

class StartViewModel extends ViewModel {
    + StartViewModel()
}

class StartView {
    - {static} VIEW_NAME: String
    - startViewModel: StartViewModel
    - startController: StartController
    - play: JButton
    - options: JButton
    - stats: JButton
    - exit: JButton
    + StartView(StartViewModel)
    + actionPerformed(e: ActionEvent): void
    + propertyChange(evt: PropertyChangeEvent): void
    - setTheme(component: JComponent, theme: Theme): void
    + getViewName(): String
    + setStartController(): void
}
StartView --> Theme
StartView --> StartViewModel
StartView --> StartController
StartView --> OptionsState

class StartController {
    - startInteractor: StartInputBoundary
    + StartController(startInputBoundary: StartInputBoundary)
    + prepareStartView(): void
    + switchToGameView(optionsState: OptionsState): void
    + switchToOptionsView(): void
    + switchToStatsView(): void
}
StartController --> StartInputBoundary
StartController --> OptionsState

interface StartInputBoundary {
    + {abstract} prepareStartView(): void
    + {abstract} prepareGameView(optionsState: OptionsState): void
    + {abstract} prepareOptionsView(): void
    + {abstract} prepareStatsView(): void
}
StartInputBoundary --> OptionsState

class StartInteractor implements StartInputBoundary {
    - startDataAccess: StartDataAccessInterface
    - gameDataAccess: GameDataAccessInterface
    - startPresenter: StartOutputBoundary
    + StartInteractor(StartDataAccessInterface, GameDataAccessInterface, StartOutputBoundary)
    + prepareStartView(): void
    + prepareGameView(optionsState: OptionsState): void
    + prepareOptionsView(): void
    + prepareStatsView(): void
}
StartInteractor --> Theme
StartInteractor --> StartOutputBoundary
StartInteractor --> StartDataAccessInterface
StartInteractor --> GameDataAccessInterface
StartInteractor --> GameState
StartInteractor --> OptionsState
StartInteractor --> AbstractWord

interface StartOutputBoundary {
    + {abstract} prepareStartView(theme: Theme): void
    + {abstract} prepareGameView(gameState: GameState): void
    + {abstract} prepareOptionsView(): void
    + {abstract} prepareStatsView(): void
}
StartOutputBoundary --> Theme
StartOutputBoundary --> GameState

interface StartDataAccessInterface {
    + getDefaultTheme(): Theme
}
StartDataAccessInterface --> Theme

class StartPresenter implements StartOutputBoundary {
    - viewManagerModel: ViewManagerModel
    - startViewModel: StartViewModel
    - gameViewModel: GameViewModel
    - optionsViewModel: OptionsViewModel
    - statsViewModel: StatsViewModel
    + StartPresenter(ViewManagerModel, StartViewModel, GameViewModel, OptionsViewModel, StatsViewModel)
    + prepareStartView(theme: Theme): void
    + prepareGameView(gameState: GameState): void
    + prepareOptionsView(): void
    + prepareStatsView(): void
}
StartPresenter --> Theme
StartPresenter --> ViewManagerModel
StartPresenter --> StartViewModel
StartPresenter --> GameViewModel
StartPresenter --> OptionsViewModel
StartPresenter --> StatsViewModel
StartPresenter --> GameState

class FileDataAccessObject implements OptionsDataAccessInterface, StatsDataAccessInterface, StartDataAccessInterface, EndDataAccessInterface {
    + getOptions(): OptionsState
    + saveOptions(options: OptionsState): void
    + getStats(): StatsState
    + saveStats(stats: StatsState): void
    + getDefaultTheme(): Theme
}
FileDataAccessObject --> OptionsState
FileDataAccessObject --> StatsState
FileDataAccessObject --> Theme

class APIDataAccessObject implements GameDataAccessInterface {
    - wordGenerator: WordGenerator
    - wordChecker: WordChecker
    - {static} MAX_TRIES: int
    + APIDataAccessObject(wordGenerator: WordGenerator, wordChecker: WordChecker)
    + getRandomWord(length: int, language: Language): String
    + isValidWord(word: String, language Language): boolean
}
APIDataAccessObject --> WordGenerator
APIDataAccessObject --> WordChecker
APIDataAccessObject --> Language

interface WordGenerator {
    + {abstract} getRandomWord(length: int): String
    + {abstract} getDefinitions(word: String, language: Language): JSONArray
}
WordGenerator --> Language

interface WordChecker {
    + {abstract} isValidWord(word: String, language: Language): boolean
}
WordChecker --> Language

abstract class API {
    # baseUrl: String
    # {static} CONTENT_TYPE_LABEL: String
    # {static} CONTENT_TYPE_JSON: String
    + API(baseUrl: String)
    + fetch(params: String): JSONArray
}

class APIWordGenerator extends API implements WordGenerator {
    - {static} languages: Map<Language, String>
    + APIWordGenerator()
    + getRandomWord(length: int, language: Language): String
}
APIWordGenerator --> Language

class APIWordChecker extends API implements WordChecker {
    - wordData: JSONObject
    - validCache: Map<String, Boolean>
    - {static} languages: Map<Language, String>
    + APIWordChecker()
    + isValidWord(word: String, language: Language): boolean
    + getDefinitions(word: String, language: Language): JSONArray
}
APIWordChecker --> Language

enum Language {
    ENGLISH
    FRENCH
    SPANISH
    ITALIAN
    GERMAN
    PORTUGUESE
}

class AppBuilder {
    - cardPanel: JPanel
    - cardLayout: CardLayout
    - viewManagerModel: ViewManagerModel
    - viewManager: ViewManager
    - startView: StartView
    - startViewModel: StartViewModel
    - gameView: GameView
    - gameViewModel: GameViewModel
    - optionsView: OptionsView
    - optionsViewModel: OptionsViewModel
    - endView: EndView
    - endViewModel: EndViewModel
    - statsView: StatsView
    - statsViewModel: StatsViewModel
    - fileDataAccessObject: FileDataAccessObject
    - apiDataAccessObject: APIDataAccessObject
    + AppBuilder()
    + addStartView(): AppBuilder
    + addEndView(): AppBuilder
    + addGameView(): AppBuilder
    + addOptionsView(): AppBuilder
    + addStatsView(): AppBuilder
    + addStartUseCase(): AppBuilder
    + addEndUseCase(): AppBuilder
    + addGameUseCase(): AppBuilder
    + addOptionsUseCase(): AppBuilder
    + addStatsUseCase(): AppBuilder
    + build(): JFrame
}
' AppBuilder --> ViewManagerModel
' AppBuilder --> ViewManager
' AppBuilder --> OptionsView
' AppBuilder --> OptionsViewModel
' AppBuilder --> GameView
' AppBuilder --> GameViewModel
' AppBuilder --> EndView
' AppBuilder --> EndViewModel
' AppBuilder --> StartView
' AppBuilder --> StartViewModel
' AppBuilder --> StatsView
' AppBuilder --> StatsViewModel

' AppBuilder --> OptionsOutputBoundary
' AppBuilder --> OptionsPresenter
' AppBulider --> OptionsInputBoundary
' AppBuilder --> OptionsInteractor
' AppBuilder --> OptionsController

' AppBuilder --> GameOutputBoundary
' AppBuilder --> GamePresenter
' AppBuilder --> GameInputBoundary
' AppBuilder --> GameInteractor
' AppBuilder --> GameController

' AppBuilder --> EndOutputBoundary
' AppBuilder --> EndPresenter
' AppBuilder --> EndInputBoundary
' AppBuilder --> EndInteractor
' AppBuilder --> EndController

' AppBuilder --> StartOutputBoundary
' AppBuilder --> StartPresenter
' AppBuilder --> StartInputBoundary
' AppBuilder --> StartInteractor
' AppBuilder --> StartController

' AppBuilder --> StatsOutputBoundary
' AppBuilder --> StatsPresenter
' AppBuilder --> StatsInputBoundary
' AppBuilder --> StatsInteractor
' AppBuilder --> StatsController

' these might be better as static
' still need to find where theme is set and used
interface Theme {
    + {abstract} getBackgroundColor(): Color
    + {abstract} getTextColor(): Color
    + {abstract} getOutlineColor(): Color
    + {abstract} getFont(): Font
    + {abstract} getColorForStatus(status: Status): Color
    + {abstract} getLetterBox(): Shape
}
Theme --> Status

' Can potentially add an AnimatedTheme interface later
' Also support for user-defined themes

class LightTheme implements Theme {
    - backgroundColor: Color
    - textColor: Color
    - outlineColor: Color
    - font: Font
    - statusColors: Map<Status, Color>
    - letterBox: Shape
    + LightTheme()
    + getBackgroundColor(): Color
    + getTextColor(): Color
    + getOutlineColor(): Color
    + getFont(): Font
    + getColorForStatus(status: Status): Color
    + getLetterBox(): Shape
}
LightTheme --> Status

class DarkTheme implements Theme {
    - backgroundColor: Color
    - textColor: Color
    - outlineColor: Color
    - font: Font
    - statusColors: Map<Status, Color>
    - letterBox: Shape
    + DarkTheme()
    + getBackgroundColor(): Color
    + getTextColor(): Color
    + getOutlineColor(): Color
    + getFont(): Font
    + getColorForStatus(status: Status): Color
    + getLetterBox(): Shape
}
DarkTheme --> Status

class SusTheme implements Theme {
    - backgroundColor: Color
    - textColor: Color
    - outlineColor: Color
    - font: Font
    - statusColors: Map<Status, Color>
    - letterBox: Shape
    + SusTheme()
    + getBackgroundColor(): Color
    + getTextColor(): Color
    + getOutlineColor(): Color
    + getFont(): Font
    + getColorForStatus(status: Status): Color
    + getLetterBox(): Shape
}
SusTheme --> Status


WordGenerator --> WordChecker

note "Can be extended to support\ndifferent languages or numbers" as N1
WordGenerator .. N1
WordChecker .. N1


@enduml